const express=require("express");const crypto=require("crypto");const fs=require("fs");const path=require("path");const nodemailer=require("nodemailer");
const app=express();const PORT=process.env.PORT||3000;const BASE_URL=(process.env.BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,"");const MP_ACCESS_TOKEN=process.env.MP_ACCESS_TOKEN;const MP_WEBHOOK_SECRET=process.env.MP_WEBHOOK_SECRET||"";const ORDER_EMAIL="agalecolombia@gmail.com";const ORDERS_FILE=path.join(__dirname,"orders.json");
app.use(express.json({limit:"1mb"}));app.use(express.static(__dirname));
const read=()=>{try{return JSON.parse(fs.readFileSync(ORDERS_FILE,"utf8"))}catch{return[]}};const write=o=>fs.writeFileSync(ORDERS_FILE,JSON.stringify(o,null,2));
function equal(a,b){const x=Buffer.from(a||""),y=Buffer.from(b||"");return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function validSig(req){if(!MP_WEBHOOK_SECRET)return true;const sig=req.headers["x-signature"]||"",rid=req.headers["x-request-id"]||"",id=String(req.body?.data?.id||req.query["data.id"]||"").toLowerCase();let ts="",v1="";for(const p of sig.split(",")){const [k,v]=p.trim().split("=");if(k==="ts")ts=v;if(k==="v1")v1=v}if(!ts||!v1||!id)return false;const m=`id:${id};request-id:${rid};ts:${ts};`;return equal(crypto.createHmac("sha256",MP_WEBHOOK_SECRET).update(m).digest("hex"),v1)}
async function mp(pathname,opts={}){const r=await fetch("https://api.mercadopago.com"+pathname,{...opts,headers:{"Content-Type":"application/json",Authorization:`Bearer ${MP_ACCESS_TOKEN}`,...(opts.headers||{})}});const t=await r.text();let d={};try{d=JSON.parse(t)}catch{}if(!r.ok)throw Error(d.message||`Mercado Pago respondió ${r.status}`);return d}
function money(n){return new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n)}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function mail(order,payment){if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS)throw Error("Faltan credenciales SMTP");const c=order.customer;const items=order.items.map(i=>`<li>${i.quantity} × ${esc(i.title)} — ${money(i.unit_price*i.quantity)}</li>`).join("");await nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||"false")==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}).sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:ORDER_EMAIL,replyTo:c.email,subject:`Pedido pagado #${order.id} - Agale Colombia`,html:`<h2>Nuevo pedido pagado #${esc(order.id)}</h2><p><b>Pago Mercado Pago:</b> ${esc(payment.id)} — ${esc(payment.status)}</p><h3>Cliente</h3><p>${esc(c.name)}<br>Email: ${esc(c.email)}<br>Teléfono: ${esc(c.phone)}<br>Documento: ${esc(c.document||"No indicado")}</p><h3>Dirección de envío</h3><p>${esc(c.address)}<br>${esc(c.city)}, ${esc(c.department)}<br>Código postal: ${esc(c.postalCode||"No indicado")}</p><p><b>Indicaciones:</b> ${esc(c.notes||"Ninguna")}</p><h3>Productos</h3><ul>${items}</ul><p><b>Total: ${money(order.total)}</b></p>`})}
app.post("/api/create-preference",async(req,res)=>{try{if(!MP_ACCESS_TOKEN)return res.status(500).json({error:"Mercado Pago no está configurado en el servidor."});const {customer,items}=req.body||{};if(!customer?.name||!customer?.email||!customer?.phone||!customer?.address||!customer?.city||!customer?.department||!Array.isArray(items)||!items.length)return res.status(400).json({error:"Faltan datos obligatorios del pedido."});const clean=items.map(i=>({id:String(i.id),title:String(i.title),quantity:Math.max(1,Number(i.quantity)),unit_price:Number(i.unit_price),currency_id:"COP",...(i.picture_url?{picture_url:String(i.picture_url)}:{})}));if(clean.some(i=>!Number.isFinite(i.unit_price)||i.unit_price<=0))return res.status(400).json({error:"Hay un producto con precio inválido."});const orderId=`AG-${Date.now()}`,total=clean.reduce((s,i)=>s+i.unit_price*i.quantity,0),order={id:orderId,customer,items:clean,total,status:"pending",createdAt:new Date().toISOString()};const orders=read();orders.push(order);write(orders);const p=await mp("/checkout/preferences",{method:"POST",body:JSON.stringify({items:clean,payer:{name:customer.name.split(" ")[0],surname:customer.name.split(" ").slice(1).join(" ")||customer.name.split(" ")[0],email:customer.email,phone:{number:customer.phone.replace(/\D/g,"")},...(customer.document?{identification:{type:"CC",number:customer.document.replace(/\D/g,"")}}:{})},shipments:{receiver_address:{street_name:customer.address,city_name:customer.city,state_name:customer.department,country_name:"Colombia",...(customer.postalCode?{zip_code:customer.postalCode}:{})}},external_reference:orderId,metadata:{order_id:orderId},back_urls:{success:`${BASE_URL}/?payment=success&order=${encodeURIComponent(orderId)}`,failure:`${BASE_URL}/?payment=failure&order=${encodeURIComponent(orderId)}`,pending:`${BASE_URL}/?payment=pending&order=${encodeURIComponent(orderId)}`},auto_return:"approved",notification_url:`${BASE_URL}/api/mercadopago/webhook`})});order.preferenceId=p.id;write(orders);res.json({checkoutUrl:p.init_point,orderId})}catch(e){console.error(e);res.status(500).json({error:e.message||"No se pudo crear el pago."})}});
app.post("/api/mercadopago/webhook",async(req,res)=>{try{if(!validSig(req))return res.status(401).json({error:"Firma de Mercado Pago inválida."});res.sendStatus(200);const type=req.body?.type||req.query.type,id=String(req.body?.data?.id||req.query["data.id"]||"");if(type!=="payment"||!id)return;const payment=await mp(`/v1/payments/${encodeURIComponent(id)}`),orderId=payment.external_reference;if(!orderId)return;const orders=read(),order=orders.find(o=>o.id===orderId);if(!order)return;order.paymentId=payment.id;order.status=payment.status;order.paymentUpdatedAt=new Date().toISOString();if(payment.status==="approved"&&!order.emailSent){try{await mail(order,payment);order.emailSent=true;order.emailSentAt=new Date().toISOString()}catch(e){console.error("Error enviando correo:",e);order.emailError=e.message}}write(orders)}catch(e){console.error("Webhook error:",e)}});
app.listen(PORT,()=>console.log(`Agale Colombia funcionando en ${BASE_URL}`));
